from datetime import datetime
from pydantic import BaseModel, field_validator, Field, EmailStr
from typing import Optional, Literal
import enum
class RequestPlan(BaseModel):
    name: str
    duration: str
    rate_of_return: float
    status: str = 'active'
    minimum: int
    maximum: int

    @field_validator("minimum")
    @classmethod
    def not_less_than_zero(cls, value):
        if value <= 0:
            raise ValueError("Cannot be less than zero")
        return value

class Balance(BaseModel):
    balance: float
    
class DailyProfit(BaseModel):
    duration_days: datetime
    daily_amount: float

class InvestmentProfit(BaseModel):
    investment_id: int
    daily_profit: list[DailyProfit]
    total_profit: float
    
class CheckPayment(BaseModel):
    status: str
    transaction_id: str
    transaction_type: str
    token: str

class ResponsePlan(BaseModel):
    id:int 
    name: str
    duration: str
    rate_of_return: float
    status: str = 'active'
    minimum: int
    maximum: int
    amount_to_receive:str 

class UpdatePlan(BaseModel):
    name: Optional[str] = None
    duration: Optional[str] = None
    rate_of_return: Optional[float] = None
    status: Optional[str] = None
    minimum: Optional[int] = None
    maximum: Optional[int] = None

class ListResponsePlan(BaseModel):
    plans:list[ResponsePlan]

class CallBack(BaseModel):
    callback:str

class RequestCryptApiSchema(BaseModel):
    callback:str
    address:str 
    pending:Optional[int] = 0
    post:Optional[int] = 0
    json_:Optional[int] = Field(default=0, alias="json")
    multi_token:Optional[int] = 0
    convert:Optional[int] = 1
    confirmations:Optional[int] = 1
    email:Optional[str] = None
    priority:Optional[str] = "default"

    class Config:
        populate_by_name = True 
   
class ResponseCryptApiSchema(BaseModel):
    address_in: str
    """Address generated by CryptAPI. You must provide it to your customer in order to receive payments."""
    
    address_out: dict
    """Your address(es), where the payment will be forwarded to, should be the same address(es) you provided."""
    
    callback_url: str
    """The callback URL you provided."""
    
    minimum_transaction_coin: float
    """The minimum transaction value coin. All the minimums can be found at our cryptocurrencies page."""
    
    priority: str
    """The confirmation priority you requested."""
    
    status: str
    """Status of the request."""

class LogResponseSchema(BaseModel):
    address_in: str = None
    """Generated address for the callback URL provided."""
    
    address_out: str = None
    """Your address(es), where the payment will be forwarded to."""
    
    callback_url: str = None
    """The callback URL you provided."""
    
    status: str = None
    """Status of the request. Should be 'success' if the request didn't fail."""
    
    notify_pending: bool = None
    """Shows if you enabled the pending callback when creating the address."""
    
    notify_confirmations: int = None
    """Number of confirmations required before sending the confirmed callback."""
    
    priority: str = None
    """The confirmation priority you requested."""
    
    callbacks: list = None
    """List of payments made to this address, together with the logs of the callbacks."""


class MakePayment(BaseModel):
    token: Literal["trc20/usdt", "eth", "btc", "trx"]
    amount:float
    plan_id:int

class SuccessCallback(BaseModel):
    """Schema for successful payment callback from CryptAPI"""
    uuid: str = Field(
        description="Unique identifier for tracking payment callbacks"
    )
    address_in: str = Field(
        description="Address generated by CryptAPI where customer sent the payment"
    )
    address_out: str = Field(
        description="Address(es) where CryptAPI forwarded the payment"
    )
    txid_in: str = Field(
        description="Transaction hash of customer's payment"
    )
    txid_out: str = Field(
        description="Transaction hash of the forwarded payment"
    )
    confirmations: int = Field(
        description="Number of blockchain confirmations"
    )
    value_coin: float = Field(
        description="Payment amount before fees"
    )
    value_coin_convert: Optional[dict] = Field(
        default=None,
        description="JSON-encoded FIAT currency conversions of value_coin"
    )
    value_forwarded_coin: float = Field(
        description="Payment amount after fees"
    )
    value_forwarded_coin_convert: Optional[dict] = Field(
        default=None,
        description="JSON-encoded FIAT currency conversions of value_forwarded_coin"
    )
    fee_coin: float = Field(
        description="Fee paid to CryptAPI"
    )
    coin: str = Field(
        description="Ticker of the coin used for payment (btc, bch, ltc, eth, trx, etc)"
    )
    price: float = Field(
        description="Coin price in USD at callback time"
    )
    pending: int = Field(
        default=0,
        description="0 for confirmed payments"
    )

class PendingCallback(BaseModel):
    pass #run a conditional in the route and then pass based on which 


{
    "uuid": "12345678-1234-5678-1234-567812345678",
    "address_in": "0x1234567890abcdef1234567890abcdef12345678",
    "address_out": "0xabcdef1234567890abcdef1234567890abcdef12",
    "txid_in": "0x9876543210fedcba9876543210fedcba98765432",
    "txid_out": "0xfedcba9876543210fedcba9876543210fedcba98",
    "confirmations": 12,
    "value_coin": 1.23456789,
    "value_coin_convert": {
        "USD": 123.45,
        "EUR": 103.45
    },
    "value_forwarded_coin": 1.2,
    "value_forwarded_coin_convert": {
        "USD": 120.0,
        "EUR": 100.8
    },
    "fee_coin": 0.03456789,
    "coin": "eth",
    "price": 1850.5,
    "pending": 0
}