from pydantic import BaseModel, field_validator, Field, EmailStr
from typing import Optional

class RequestPlan(BaseModel):
    name: str
    duration: str
    rate_of_return: float
    status: str = 'active'
    minimum: int
    maximum: int

    @field_validator("minimum")
    @classmethod
    def not_less_than_zero(cls, value):
        if value <= 0:
            raise ValueError("Cannot be less than zero")
        return value


class ResponsePlan(BaseModel):
    id:int 
    name: str
    duration: str
    rate_of_return: float
    status: str = 'active'
    minimum: int
    maximum: int
    amount_to_receive:str 

class UpdatePlan(BaseModel):
    name: Optional[str] = None
    duration: Optional[str] = None
    rate_of_return: Optional[float] = None
    status: Optional[str] = None
    minimum: Optional[int] = None
    maximum: Optional[int] = None

class ListResponsePlan(BaseModel):
    plans:list[ResponsePlan]

class CallBack(BaseModel):
    callback:str

class RequestCryptApiSchema(BaseModel):
    callback:str
    address:str 
    pending:Optional[int] = 0
    post:Optional[int] = 0
    json_:Optional[int] = Field(default=0, alias="json")
    multi_token:Optional[int] = 0
    convert:Optional[int] = 0
    confirmation:Optional[int] = 1
    email:Optional[str] = None
    priority:Optional[str] = "default"

    class Config:
        populate_by_name = True 
   
class ResponseCryptApiSchema(BaseModel):
    address_in: str
    """Address generated by CryptAPI. You must provide it to your customer in order to receive payments."""
    
    address_out: str
    """Your address(es), where the payment will be forwarded to, should be the same address(es) you provided."""
    
    callback_url: str
    """The callback URL you provided."""
    
    minimum_transaction_coin: float
    """The minimum transaction value coin. All the minimums can be found at our cryptocurrencies page."""
    
    priority: str
    """The confirmation priority you requested."""
    
    status: str
    """Status of the request."""

class LogResponseSchema(BaseModel):
    address_in: str = None
    """Generated address for the callback URL provided."""
    
    address_out: str = None
    """Your address(es), where the payment will be forwarded to."""
    
    callback_url: str = None
    """The callback URL you provided."""
    
    status: str = None
    """Status of the request. Should be 'success' if the request didn't fail."""
    
    notify_pending: bool = None
    """Shows if you enabled the pending callback when creating the address."""
    
    notify_confirmations: int = None
    """Number of confirmations required before sending the confirmed callback."""
    
    priority: str = None
    """The confirmation priority you requested."""
    
    callbacks: list = None
    """List of payments made to this address, together with the logs of the callbacks."""


class MakePayment(BaseModel):
    token:str
    amount:float

class SuccessCallback(BaseModel):
    pass 

class PendingCallback(BaseModel):
    pass #run a conditional in the route and then pass based on which 